/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_hibaku;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author userpc
 */
public class Form_Donatur extends javax.swing.JDialog {

    /**
     * Creates new form Form_Donatur
     */
    
    Connection kon;
    String nik;
    public Form_Donatur(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        kon=koneksi.getKoneksi("localhost", "3306", "root", "","hibaku");
        cbbarangdonasidonatur.disable();
            
    }
    
    void showdata(){
        try {
           Statement stmt = kon.createStatement();
           String query = "select * from donatur where NIK = '"+nik+"'";
           ResultSet rs = stmt.executeQuery(query);
           rs.first();
           txtnamadonatur.setText(rs.getString("NAMA_DONATUR"));
           txtnikdonatur.setText(rs.getString("NIK"));
           txtalamatdonatur.setText(rs.getString("ALAMAT_DONATUR"));
           txtjumlahdonasidonatur.setText(rs.getString("JUMLAH_DONASI"));
           cbbarangdonasidonatur.setSelectedItem(rs.getString("BARANG_DONASI"));
           String jenis = rs.getString("JENIS_DONASI");
            if (jenis.equals("Barang")) {
          rbbarangdonatur.setSelected(true);
     } else {
          rbuangdonatur.setSelected(true);
     }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "terjadi kesalahan");
        }
    }
    public void Simpandata(){
        String donasi="";
        String barang="";
        String nama     = txtnamadonatur.getText();
        String nik      = txtnikdonatur.getText();
        String alamat   = txtalamatdonatur.getText();
        String jumlah   = txtjumlahdonasidonatur.getText();
        
        if(rbbarangdonatur.isSelected()){
            donasi = "Barang";
        }
        if(rbuangdonatur.isSelected()){
            donasi = "Uang";
        }
        
        if(cbbarangdonasidonatur.getSelectedItem()=="HEWAN TERNAK"){
        barang="HEWAN TERNAK";}
        else if (cbbarangdonasidonatur.getSelectedItem()=="PAKAN TERNAK"){
        barang="PAKAN TERNAK"; }
        else if (cbbarangdonasidonatur.getSelectedItem()=="ALAT"){
        barang="ALAT";}
        else if (cbbarangdonasidonatur.getSelectedItem()=="BIBIT"){
        barang="BIBIT";
        }else{
        barang="";
        }
        try {
            Statement stmt =kon.createStatement();
            String query = "INSERT INTO donatur (NAMA_DONATUR,NIK,ALAMAT,JENIS_DONASI,BARANG_DONASI,JUMLAH_DONASI)"
                    + "VALUES('"+nama+"','"+nik+"','"+alamat+"','"+donasi+"','"+barang+"','"+jumlah+"')";
            System.out.println(query);
            int berhasil = stmt.executeUpdate(query);
            if (berhasil == 1) {
                JOptionPane.showMessageDialog(null,"DATA BERHASIL DIMASUKKAN");
            }else{
                   JOptionPane.showMessageDialog(null,"DATA GAGAL DIMASUKKAN");
            }
   
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "TERJADI KESALAHAN");
        }
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtnamadonatur = new javax.swing.JTextField();
        txtnikdonatur = new javax.swing.JTextField();
        txtalamatdonatur = new javax.swing.JTextField();
        rbuangdonatur = new javax.swing.JRadioButton();
        rbbarangdonatur = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cbbarangdonasidonatur = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtjumlahdonasidonatur = new javax.swing.JTextField();
        btnsimpan = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("FORM DONATUR");

        jLabel2.setText("NAMA DONATUR");

        jLabel3.setText("NIK");

        jLabel4.setText("ALAMAT");

        jLabel5.setText("JEINIS DONASI");

        jLabel6.setText(":");

        jLabel7.setText(":");

        jLabel8.setText(":");

        jLabel9.setText(":");

        buttonGroup1.add(rbuangdonatur);
        rbuangdonatur.setText("UANG");
        rbuangdonatur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbuangdonaturActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbbarangdonatur);
        rbbarangdonatur.setText("BARANG");
        rbbarangdonatur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbbarangdonaturActionPerformed(evt);
            }
        });

        jLabel10.setText("BARANG DONASI");

        jLabel11.setText(":");

        cbbarangdonasidonatur.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-PILIH-", "HEWAN TERNAK", "PAKAN TERNAK", "ALAT", "BIBIT" }));

        jLabel12.setText("JUMLAH DONASI");

        jLabel13.setText(":");

        btnsimpan.setText("SIMPAN");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        btnreset.setText("RESET");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(33, 33, 33)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel10)
                                .addComponent(jLabel12))
                            .addGap(56, 56, 56)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addGap(18, 18, 18)
                                    .addComponent(rbuangdonatur)
                                    .addGap(29, 29, 29)
                                    .addComponent(rbbarangdonatur))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtalamatdonatur, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel7))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtnamadonatur)
                                        .addComponent(txtnikdonatur, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addGap(18, 18, 18)
                                    .addComponent(cbbarangdonasidonatur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtjumlahdonasidonatur))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(249, 249, 249)
                            .addComponent(jLabel1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(btnsimpan)
                        .addGap(93, 93, 93)
                        .addComponent(btnreset)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(txtnamadonatur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(txtnikdonatur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(txtalamatdonatur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9)
                    .addComponent(rbuangdonatur)
                    .addComponent(rbbarangdonatur))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(cbbarangdonasidonatur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(txtjumlahdonasidonatur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnreset, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbuangdonaturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbuangdonaturActionPerformed
        // TODO add your handling code here:
        if(rbuangdonatur.isSelected()){
            cbbarangdonasidonatur.disable();
        }
    }//GEN-LAST:event_rbuangdonaturActionPerformed

    private void rbbarangdonaturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbbarangdonaturActionPerformed
        // TODO add your handling code here:
        if(rbbarangdonatur.isSelected()){
            cbbarangdonasidonatur.enable();
        }
    }//GEN-LAST:event_rbbarangdonaturActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
    Simpandata();
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
    txtnamadonatur.setText(null);
    txtnikdonatur.setText(null);
    txtalamatdonatur.setText(null);
    txtjumlahdonasidonatur.setText(null);
    rbuangdonatur.setSelected(false);
    rbbarangdonatur.setSelected(false);
    
    }//GEN-LAST:event_btnresetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Donatur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Donatur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Donatur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Donatur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Form_Donatur dialog = new Form_Donatur(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btnsimpan;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbbarangdonasidonatur;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton rbbarangdonatur;
    private javax.swing.JRadioButton rbuangdonatur;
    private javax.swing.JTextField txtalamatdonatur;
    private javax.swing.JTextField txtjumlahdonasidonatur;
    private javax.swing.JTextField txtnamadonatur;
    private javax.swing.JTextField txtnikdonatur;
    // End of variables declaration//GEN-END:variables
}
