/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_hibaku;

import java.sql.Connection;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author userpc
 */
public class Form_Penerima extends javax.swing.JDialog {

    /**
     * Creates new form Form_Penerima
     */
    Connection kon;
    public Form_Penerima(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        kon=koneksi.getKoneksi("localhost", "3306", "root", "","hibaku");
        cmbbarangditerima.disable();
    }
public void Simpandata(){
 String donasi="";
 String barang="";
 String nama=txtnamapenerima.getText();
 String nik=txtnikpenerima.getText();
 String kelompok=txtnamakelompokpenerima.getText();
 String alamat=txtalamatpenerima.getText();
 String wilayah=txtwilayahpenerima.getText();
 String jumlah=txtjumlahditerima.getText();
 String keterangan=txtketerangan.getText();
 
  if(rbbarangpenerima.isSelected()){
            donasi = "Barang";}
  if(rbuangpenerima.isSelected()){
            donasi = "Uang";}
            
  if(cmbbarangditerima.getSelectedItem()=="DOMBA JANTAN"){
        barang="DOMBA JANTAN";}
        else if (cmbbarangditerima.getSelectedItem()=="DOMBA BETINA"){
        barang="DOMBA BETINA"; }
        else if (cmbbarangditerima.getSelectedItem()=="DOMBA PETERNAK JANTAN"){
        barang="DOMBA PETERNAK JANTAN";}
        else if (cmbbarangditerima.getSelectedItem()=="DOMBA PETERNAK BETINA")
        barang="DOMBA PETERNAK BETINA";
        else if (cmbbarangditerima.getSelectedItem()=="SAPI POTONG BETINA (PEDET)")
        barang="SAPI POTONG BETINA (PEDET)";
        else if (cmbbarangditerima.getSelectedItem()=="SAPI PERAH")
        barang="SAPI PERAH";
        else if (cmbbarangditerima.getSelectedItem()=="KERBAU")
        barang="KERBAU";
        else if (cmbbarangditerima.getSelectedItem()=="ITIK")
        barang="ITIK";
        else if (cmbbarangditerima.getSelectedItem()=="ITIK PADJAJARAN")
        barang="ITIK PADJAJARAN";
        else if (cmbbarangditerima.getSelectedItem()=="(DOC)AYAM PETELUR")
        barang="(DOC)AYAM PETELUR";
        else if (cmbbarangditerima.getSelectedItem()=="BIBIT TERNAK")
        barang="BIBIT TERNAK";
        else if (cmbbarangditerima.getSelectedItem()=="PAKAN TERNAK")
        barang="PAKAN TERNAK";
        else if (cmbbarangditerima.getSelectedItem()=="OBAT-OBATAN")
        barang="OBAT-OBATAN";
        else if (cmbbarangditerima.getSelectedItem()=="ALAT DAN MESIN PETERNAKAN"){
        barang="ALAT DAN MESIN PETERNAKAN";
        }else{
        barang="";
        }
  try {
            Statement stmt =kon.createStatement();
            String query = "INSERT INTO penerima (NAMA_PENERIMA,NIK,NAMA_KELOMPOK,ALAMAT,WILAYAH,DONASI_DITERIMA,BARANG_DITERIMA,JUMLAH,KETERANGAN)"
                    + "VALUES('"+nama+"','"+nik+"','"+kelompok+"','"+alamat+"','"+wilayah+"','"+donasi+"','"+barang+"','"+jumlah+"','"+keterangan+"')";
            System.out.println(query);
            int berhasil = stmt.executeUpdate(query);
            if (berhasil == 1) {
                JOptionPane.showMessageDialog(null,"DATA BERHASIL DIMASUKKAN");
            }else{
                   JOptionPane.showMessageDialog(null,"DATA GAGAL DIMASUKKAN");
            }            }
            catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "TERJADI KESALAHAN");
}}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtnamapenerima = new javax.swing.JTextField();
        txtnikpenerima = new javax.swing.JTextField();
        txtnamakelompokpenerima = new javax.swing.JTextField();
        txtalamatpenerima = new javax.swing.JTextField();
        txtwilayahpenerima = new javax.swing.JTextField();
        rbuangpenerima = new javax.swing.JRadioButton();
        rbbarangpenerima = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cmbbarangditerima = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtjumlahditerima = new javax.swing.JTextField();
        btnsimpan = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtketerangan = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("FORM PENERIMA");

        jLabel2.setText("NAMA KETUA KELOMPOK");

        jLabel3.setText("NIK");

        jLabel4.setText("NAMA KELOMPOK");

        jLabel5.setText("ALAMAT");

        jLabel6.setText(":");

        jLabel7.setText(":");

        jLabel8.setText(":");

        jLabel9.setText(":");

        jLabel10.setText("KECAMATAN");

        jLabel11.setText(":");

        jLabel12.setText("DONASI YANG DITERIMA");

        jLabel13.setText(":");

        txtalamatpenerima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtalamatpenerimaActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbuangpenerima);
        rbuangpenerima.setText("UANG");

        buttonGroup1.add(rbbarangpenerima);
        rbbarangpenerima.setText("BARANG");
        rbbarangpenerima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbbarangpenerimaActionPerformed(evt);
            }
        });

        jLabel14.setText("SARANA PRODUKSI TERNAK");

        jLabel15.setText(":");

        cmbbarangditerima.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-PILIH-", "DOMBA JANTAN", "DOMBA BETINA", "DOMBA PETERNAK JANTAN", "DOMBA PETERNAK BETINA", "SAPI POTONG BETINA (PEDET)", "SAPI PERAH", "KERBAU", "ITIK", "ITIK PADJAJARAN", "(DOC) AYAM PETELUR", "BIBIT TERNAK", "PAKAN TERNAK", "OBAT-OBATAN", "ALAT DAN MESIN PETERNAKAN", " " }));

        jLabel16.setText("JUMLAH YANG DITERIMA");

        jLabel17.setText(":");

        btnsimpan.setText("SIMPAN");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        btnreset.setText("RESET");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });

        jLabel18.setText("KETERANGAN ");

        jLabel19.setText(":");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12))
                        .addGap(87, 87, 87)
                        .addComponent(rbuangpenerima)
                        .addGap(48, 48, 48)
                        .addComponent(rbbarangpenerima))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(313, 313, 313)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel19))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel17))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel15)))
                                .addComponent(jLabel11)
                                .addComponent(jLabel9)
                                .addComponent(jLabel8)
                                .addComponent(jLabel7)
                                .addComponent(jLabel6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbbarangditerima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtjumlahditerima, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnsimpan)
                                .addGap(73, 73, 73)
                                .addComponent(btnreset))
                            .addComponent(txtwilayahpenerima, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                            .addComponent(txtalamatpenerima, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                            .addComponent(txtnamakelompokpenerima, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                            .addComponent(txtnikpenerima, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                            .addComponent(txtnamapenerima, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                            .addComponent(txtketerangan))))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(txtnamapenerima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(txtnikpenerima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(txtnamakelompokpenerima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9)
                    .addComponent(txtalamatpenerima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(txtwilayahpenerima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(rbuangpenerima)
                    .addComponent(rbbarangpenerima))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(cmbbarangditerima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(txtjumlahditerima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(txtketerangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnreset, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtalamatpenerimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtalamatpenerimaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtalamatpenerimaActionPerformed

    private void rbbarangpenerimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbbarangpenerimaActionPerformed
        if(rbbarangpenerima.isSelected()){
            cmbbarangditerima.enable();}
    }//GEN-LAST:event_rbbarangpenerimaActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        Simpandata();
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
    txtnamapenerima.setText(null);
    txtnikpenerima.setText(null);
    txtnamakelompokpenerima.setText(null);
    txtalamatpenerima.setText(null);
    txtwilayahpenerima.setText(null);
    rbuangpenerima.setSelected(false);
    rbbarangpenerima.setSelected(false);
    txtjumlahditerima.setText(null);
    txtketerangan.setText(null);
    }//GEN-LAST:event_btnresetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Penerima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Penerima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Penerima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Penerima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Form_Penerima dialog = new Form_Penerima(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btnsimpan;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox<String> cmbbarangditerima;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton rbbarangpenerima;
    private javax.swing.JRadioButton rbuangpenerima;
    private javax.swing.JTextField txtalamatpenerima;
    private javax.swing.JTextField txtjumlahditerima;
    private javax.swing.JTextField txtketerangan;
    private javax.swing.JTextField txtnamakelompokpenerima;
    private javax.swing.JTextField txtnamapenerima;
    private javax.swing.JTextField txtnikpenerima;
    private javax.swing.JTextField txtwilayahpenerima;
    // End of variables declaration//GEN-END:variables

   
    }

