/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_hibaku;

import java.io.File;
import java.io.FileWriter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JTable;

/**
 *
 * @author userpc
 */
public class laporan_donatur extends javax.swing.JDialog {

    /**
     * Creates new form laporan_perkembangan
     */
    Connection kon;
   

    public laporan_donatur(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        kon=koneksi.getKoneksi("localhost", "3306", "root", "","hibaku");
        showData();
        
    }

    DefaultTableModel dtm;


    public void showData() {
        String[] kolom = {"No","NAMA DONATUR","NIK","ALAMAT","JENIS DONASI","BARANG DONASI","JUMLAH"};
        dtm = new DefaultTableModel (null,kolom);
        try {
            Statement stmt = kon.createStatement();
            String query = "SELECT*FROM donatur";
            ResultSet rs = stmt.executeQuery (query);
            int No = 1;
            while (rs.next ()){
            String nama = rs.getString ("NAMA_DONATUR");
            String nik = rs.getString("NIK");
            String alamat = rs.getString("ALAMAT");
            String jenis = rs.getString("JENIS_DONASI");
            String barang = rs.getString("BARANG_DONASI");
            String jumlah = rs.getString("JUMLAH_DONASI");
            dtm.addRow(new String []{No+"", nama, nik, alamat, jenis, barang, jumlah});
            No++;
            
            }
        
        }
        catch (SQLException ex){
        ex.printStackTrace();
        
        }
        tbldonatur.setModel(dtm);
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbldonatur = new javax.swing.JTable();
        btndelete = new javax.swing.JButton();
        btncari = new javax.swing.JButton();
        txtcari = new javax.swing.JTextField();
        btnconvert = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tbldonatur.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbldonatur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbldonaturMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbldonatur);

        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btncari.setText("Search");
        btncari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncariActionPerformed(evt);
            }
        });

        txtcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcariActionPerformed(evt);
            }
        });

        btnconvert.setText("Convert");
        btnconvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconvertActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btncari)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnconvert)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btndelete))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1042, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btndelete)
                    .addComponent(btncari)
                    .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnconvert))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int baris;
    private void tbldonaturMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbldonaturMouseClicked
        baris = tbldonatur.getSelectedRow();

    }//GEN-LAST:event_tbldonaturMouseClicked

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        int ok = JOptionPane.showConfirmDialog(null,"Apakah Anda yakin?","Konfirmasi",JOptionPane.YES_NO_OPTION);
        String delete = tbldonatur.getValueAt(baris, 2).toString();
        if(ok==0){
        try {
            Statement stmt = kon.createStatement();
            String query = "DELETE FROM donatur WHERE NIK = '" +delete+ "'";
            int berhasil = stmt.executeUpdate(query);
            if (berhasil == 1) {
                JOptionPane.showMessageDialog(null, "DATA BERHASIL DIHAPUS");
                dtm.getDataVector().removeAllElements();
                showData();
            } else {
                JOptionPane.showMessageDialog(null, "DATA GAGAL DIHAPUS");
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }}
    }//GEN-LAST:event_btndeleteActionPerformed
    public static int statusSearching = 0;
    private void btncariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncariActionPerformed
       
        
        try
        {
            Statement st = kon.createStatement();
            String search = txtcari.getText();
            ResultSet rs = st.executeQuery("SELECT * FROM donatur WHERE NIK like '%"+search+"%' "
                    + "OR NAMA_DONATUR like '%"+search+"%' "
                            + "OR ALAMAT like '%"+search+"%' "
                                    + "OR JENIS_DONASI like '%"+search+"%' "
                                            + "OR BARANG_DONASI like '%"+search+"%' "
                                                    + "OR JUMLAH_DONASI like '%"+search+"%'");
            DefaultTableModel dtm = (DefaultTableModel) tbldonatur.getModel();

            dtm.setRowCount(0);
            String [] data = new String[7];
            int i = 1;
            int No = 1;
            while(rs.next())
            {
                
                
                
            String nama = rs.getString ("NAMA_DONATUR");
            String nik = rs.getString("NIK");
            String alamat = rs.getString("ALAMAT");
            String jenis = rs.getString("JENIS_DONASI");
            String barang = rs.getString("BARANG_DONASI");
            String jumlah = rs.getString("JUMLAH_DONASI");
            dtm.addRow(new String []{No+"", nama, nik, alamat, jenis, barang, jumlah});
            No++;
            i++;
            }
            rs.close();
            txtcari.setText("");
        }
        catch(Exception ex)  {
            JOptionPane.showMessageDialog(null,"Data yang Anda cari Tidak dapat Ditemukan");
            System.err.println("error (search) : " +ex);
        } 
    }//GEN-LAST:event_btncariActionPerformed

    private void txtcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcariActionPerformed

    }//GEN-LAST:event_txtcariActionPerformed
public void exportCalc(JTable tabel,File f)
	{
		try
		{
			int a,b;
			dtm = (DefaultTableModel) tabel.getModel();
			FileWriter fw = new FileWriter(f);
			for(a=0;a<dtm.getColumnCount();a=a+1)
			{
				fw.write(dtm.getColumnName(a) + " \t");
			}
			fw.write(" \n");
				for(a=0;a<dtm.getRowCount();a=a+1)
				{
					for(b=0;b<dtm.getColumnCount();b=b+1)
					{
						fw.write(dtm.getValueAt(a, b).toString() + " \t");
					}
					fw.write(" \n");
				}
				fw.close();
			JOptionPane.showMessageDialog(null,"Data berhasil di export ke Excel");
		}
		catch(Exception ex)
		{
			System.out.println(ex);
		}
	}
    private void btnconvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconvertActionPerformed
        exportCalc(tbldonatur, new File("C:/Users/userpc/Documents/laporan donatur.xls"));
    }//GEN-LAST:event_btnconvertActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(laporan_donatur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(laporan_donatur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(laporan_donatur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(laporan_donatur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                laporan_donatur dialog = new laporan_donatur(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncari;
    private javax.swing.JButton btnconvert;
    private javax.swing.JButton btndelete;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbldonatur;
    private javax.swing.JTextField txtcari;
    // End of variables declaration//GEN-END:variables
}
